#exec and input paths and hardware settings
input_files: "" #(REQUIRED)absolute path(s) must be provided by user in config file, if > 1, comma separated
threads: 4
#genome file and genomic annotations
organism: "hs" #(OPTIONAL) allowed values are "hs" for human and "mm" for mouse
genome_fasta: "" #(OPTIONAL) you can specify your own genome file, if not specified GRCh38/GRCm39 primary assembly from gencode v45 will be automatically downloaded
gtf: "" #(OPTIONAL) you can specify your own gtf file (compatible with genome), if not specified basic annotation for GRCh38/GRCm39 primary assembly from gencode v45 will be automatically downloaded
genome_version: "" #(OPTIONAL) you can specify your own genome/gtf version; default: GRCh38/GRCm39 primary assembly from gencode v45
annot_rank: "" #(OPTIONAL) you can specify your own annotation rank file, suggesed when using your own genome; default: parpipe2_dir/annotation/annot_ranks.txt
#adapter trimming and reads collapsing
three_prime_adapter: "" #(REQUIRED!!!) put your 3'adapter sequence
five_prime_adapter: "" #(REQUIRED!!!) your 5'adapter sequence
nextseq: False #(OPTIONAL) put True or 1 if your sequencing run was on NextSeq machine
cutadapt_params1: "-b CGTACGCGGGTTTAAACGA -b CTCATCTTGGTCGTACGCGGAATAGTTTAAACTGT -n 3 -j 0 -m 15 -M 50 --max-n 1" #(OPTIONAL) - additional cutadapt parameters
cutadapt_params2: "" #(OPTIONAL) leave empty to ommit this step, if you want to perform second trimming put all cutadapt parameters for 2nd trimming here (including adapters)
umi: "" #(OPTIONAL) leave empty if you don't have UMIs, for 5' UMIs positive integer equal UMI length, if 3'UMIs - negative integer equal UMI length
#removing repetitive elements
rem_rep: ""  #(OPTIONAL) leave empty to omit this step, put True or 1 if you want to remove repetitive elements
rep_idx: "" #(OPTIONAL) default: parpipe2_dir/annotation/{organism}/rep_idx
star_rem_reps_params: "--runMode alignReads --genomeLoad NoSharedMemory --alignEndsType EndToEnd --outSAMunmapped Within --outFilterMultimapNmax 30 --outFilterMultimapScoreRange 1 --outSAMtype BAM Unsorted --outFilterType BySJout --outBAMcompression 10 --outReadsUnmapped Fastx --outFilterScoreMin 10 --outSAMattrRGline ID:foo --outSAMattributes All --outSAMmode Full" #(OPTIONAL)
#genome alignment
aligner: ""  #(OPTIONAL) default bowtie, use 'S', 's', 'STAR' or 'star' to switch to STAR
bowtie_index_dir: "" #(OPTIONAL) default - will be created automatically in your working dir if aligner will be set to bowtie
bowtie_index_params: "" #(OPTIONAL)
bowtie_map_params: "-v 1 -m 10 --best --strata -S" #(OPTIONAL)
star_index_dir: "" #(OPTIONAL) default - will be created automatically in your working dir if aligner will be set to STAR
star_index_params: "--runMode genomeGenerate --sjdbOverhang 100" #(OPTIONAL)
star_map_params: "--runMode alignReads --genomeLoad NoSharedMemory --alignEndsType EndToEnd --outSAMunmapped Within --outFilterMultimapNmax 1 --outFilterMultimapScoreRange 1 --outSAMattributes All --outSAMtype BAM Unsorted --outFilterType BySJout --outFilterMismatchNoverReadLmax 0.05 --outSAMattrRGline ID:foo --outStd Log --outBAMcompression 10 --outSAMmode Full" #(OPTIONAL)
#PARalyzer params
paralyzer_memory: "4G" #(OPTIONAL)
BANDWIDTH: 3 #(OPTIONAL)
CONVERSION: "T>C" #(OPTIONAL), possible choices "T>C", "G>A"
MINIMUM_READ_COUNT_PER_GROUP: 5 #(OPTIONAL),
MINIMUM_READ_COUNT_PER_CLUSTER: 2 #(OPTIONAL)
MINIMUM_READ_COUNT_FOR_KDE: 3 #(OPTIONAL)
MINIMUM_CLUSTER_SIZE: 11 #(OPTIONAL)
MINIMUM_CONVERSION_LOCATIONS_FOR_CLUSTER: 2 #(OPTIONAL)
MINIMUM_CONVERSION_COUNT_FOR_CLUSTER: 2 #(OPTIONAL)
MINIMUM_READ_COUNT_FOR_CLUSTER_INCLUSION: 1 #(OPTIONAL)
MINIMUM_READ_LENGTH: 15 #(OPTIONAL)
MAXIMUM_NUMBER_OF_NON_CONVERSION_MISMATCHES: 1 #(OPTIONAL)
signal_extension: "EXTEND_BY_READ" ##(OPTIONAL) one of 'EXTEND_BY_READ', 'HAFNER_APPROACH', 'ADDITIONAL_NUCLEOTIDES_BEYOND_SIGNAL'
ADDITIONAL_NUCLEOTIDES_BEYOND_SIGNAL: 2 #only valid when signal_extension : 'ADDITIONAL_NUCLEOTIDES_BEYOND_SIGNAL'
use_pcr_duplicates: False #(OPTIONAL) change to True to force PARalyzer to treat pcr duplicates as individual reads (will increase number of clusters, but also false positives)
#motif enrichment params
motif_enrichment_method: "meme" #(OPTIONAL), possible choices "meme", "dreme", "streme"
motif_enrichment_params: "-dna -mod anr -evt 0.05 -minw 3" #(OPTIONAL); be aware that some prameters are specific for enrichment method chosen
